export const SERVICE_AVAILABLE = 'SERVICE_AVAILABLE';
export const GET_STATISTICS = 'GET_STATISTICS';
export const GET_DOCTORS = 'GET_DOCTORS';
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_BLOGS = 'GET_BLOGS';
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';